### ISSUE TITLE
Doesn't work 

### ISSUE THREAD

**Issue by whiteeagle44** [Shigma/vuepress-plugin-mathjax#12]
The output is identical to the input, even on the documentation website: 
https://vuepress.github.io/en/plugins/mathjax/#usage

The latex katex rendering plugin (https://github.com/zlliang/vuepress-plugin-latex) doesn't work either. 

It would be cool, if somebody fixed it as it's an important feature.

**Comment by shigma** [comment]
This plugin was broken by `vuepress@1.0.0-alpha.48`, and this problem is solved by `vuepress-plugin-mathjax@1.2.8`.

**Comment by xiaoqisz** [comment]
> This plugin was broken by `vuepress@1.0.0-alpha.48`, and this problem is solved by `vuepress-plugin-mathjax@1.2.8`.

Fix mao xian
