### ISSUE TITLE
Formulas inside tables are not parsed

### ISSUE THREAD

**Issue by songololo** [Shigma/vuepress-plugin-mathjax#3]
Firstly, a huge thanks for creating this plugin.

The only bug I've run into so far is that formulas inside markdown tables are not parsed.

e.g. this doesn't work:
```
| key | formula | notes |
|-----|---------|-------|
| node_density | $$\sum_{j\neq{i}} w_{j}$$ | The default $w=1$ reduces...
```

**Comment by shigma** [comment]
Currently, you should always use single $ to display inline TeX.

- The default $w=1$ reduces... ✔️ 
- $$\sum_{j\neq{i}} w_{j}$$ :x:

**Comment by songololo** [comment]
Within the table cells I'd like the display-style (larger and centred), hence the use of the display style.

Here is an [example](https://cityseer.github.io/cityseer/metrics/networks.html#compute-centrality) (the example page currently uses mathjax loaded from CDN, you might need to scroll down a little bit to see the table).

**Comment by chuxubank** [comment]
@songololo You can use `$\displaystyle\sum_{j\neq{i}} w_{j}$` to get larger display, but not centered...
Try this
```
| key          |               formula                | notes                        |
| ------------ | :----------------------------------: | ---------------------------- |
| node_density | $\displaystyle\sum_{j\neq{i}} w_{j}$ | The default $w=1$ reduces... |
```

**Comment by songololo** [comment]
I noticed that including an invisible character after the math content would cause the maths to be parsed successfully.

But I see that the issue now appears fixed in `v1.1.0`? (Seems to work on dev).

**Comment by shigma** [comment]
> I noticed that including an invisible character after the math content would cause the maths to be parsed successfully.
> 
> But I see that the issue now appears fixed in `v1.1.0`? (Seems to work on dev).

Do you mean #2?

**Comment by songololo** [comment]
No, sorry, I meant it works when running `vuepress dev` (and it also worked with `vuepress build`) with version `v1.1.0`.

Originally, I couldn't get inline or display style maths to render in markdown tables.

**Comment by shigma** [comment]
@songololo Can you check out whether this issue was fixed?

**Comment by songololo** [comment]
@Shigma yes it is working, thanks!
