### ISSUE TITLE
Version 1.2.3 breaks paths to mathjax fonts

### ISSUE THREAD

**Issue by songololo** [Shigma/vuepress-plugin-mathjax#4]
Version 1.2.3 seems to create an issue with the paths to the mathjax fonts:

e.g. on a local test server:

<img width="1455" alt="Screenshot 2019-03-31 at 11 05 48" src="https://user-images.githubusercontent.com/4347878/55287800-a5548600-53a5-11e9-833a-4b79256b5a89.png">

e.g. on a deployed vuepress site:

<img width="1575" alt="Screenshot 2019-03-31 at 11 08 43" src="https://user-images.githubusercontent.com/4347878/55287799-a2f22c00-53a5-11e9-83d2-8b7fb2490d4e.png">

Have gone back to v1.2.2 which still works as before.

**Comment by shigma** [comment]
Sorry about the issue. I have just published a new version 1.2.4. Can you help check whether it solves your problem?

**Comment by songololo** [comment]
Fixed! Thanks.
