### ISSUE TITLE
Katex vs mathjax v3

### ISSUE THREAD

**Issue by faroit** [Shigma/vuepress-plugin-mathjax#5]
This is a great and useful plugin. I was successfully using https://github.com/iktakahiro/markdown-it-katex together with vuepress for quite some time now without any problems. Is there a specific reason why mathjax was chosen over katex?

**Comment by faroit** [comment]
Should this be closed then?

**Comment by shigma** [comment]
Well thanks for the issue anyway. I made the plugin for many reasons. The major reason is that mathjax3 can run on server side without a browser environment, which means a smaller bundle size. Also, katex's client-side-rendering may conflict with Vue.

**Comment by shigma** [comment]
Closed but further discussions are welcomed.
